### ISSUE TITLE
只配置了一个REDIS实例，出现下面的错误

### ISSUE THREAD

**Issue by lisqorz** [wayslog/aster#8]
```shell
$ RUST_BACKTRACE=full aster
[2019-03-14T09:10:57Z ERROR libaster::cluster] fail to init cluster with given server due Critical
thread 'cluster-test-redis-cluster-1' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:997:5
stack backtrace:
   0:        0x101dcd123 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h9a87463918f2aff9
   1:        0x101dcb2cd - std::panicking::default_hook::{{closure}}::h519f1fd4b67636f1
   2:        0x101dc9ca5 - std::panicking::rust_panic_with_hook::h4a3495c63f64f755
   3:        0x101dd1a6d - std::panicking::continue_panic_fmt::h3de7ba5e03709cd8
   4:        0x101dd8228 - rust_begin_unwind
   5:        0x101ddc959 - core::panicking::panic_fmt::h3232e370fc290bbc
   6:        0x101d04faf - core::result::unwrap_failed::hb2654515faed6d35
   7:        0x101cdd3a8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h85ef338ab55caf5d
   8:        0x101cde064 - <F as alloc::boxed::FnBox<A>>::call_box::h1c6938080f63b8e1
   9:        0x101dd9147 - std::sys::unix::thread::Thread::new::thread_start::h2ccd51efe09a6d88
  10:     0x7fff6d3fc304 - _pthread_body
  11:     0x7fff6d3ff26e - _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:997:5
stack backtrace:
   0:        0x101dcd123 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h9a87463918f2aff9
   1:        0x101dcb2cd - std::panicking::default_hook::{{closure}}::h519f1fd4b67636f1
   2:        0x101dc9ca5 - std::panicking::rust_panic_with_hook::h4a3495c63f64f755
   3:        0x101dd1a6d - std::panicking::continue_panic_fmt::h3de7ba5e03709cd8
   4:        0x101dd8228 - rust_begin_unwind
   5:        0x101ddc959 - core::panicking::panic_fmt::h3232e370fc290bbc
   6:        0x101d0505e - core::result::unwrap_failed::hb5ad3bcad46a4ef9
   7:        0x101c9ad15 - libaster::run::hc735f5d92683e87a
   8:        0x101de67a0 - aster::main::h087a0281b5783cfb
   9:        0x101de6385 - std::rt::lang_start::{{closure}}::h8dab523c8f9733a4
  10:        0x101de65a8 - main
```
**配置文件**

```toml

[[clusters]]
# name of the cluster. Each cluster means one front-end port.

name="test-redis-cluster"

# listen_addr means the cluster font end serve address.

listen_addr="0.0.0.0:9001"

# cache_type only support memcache|redis|redis_cluster

cache_type="redis_cluster"

# servers means cache backend. support two format:
# for cache_type is memcache or redis, you can set it as:
#
#
# as you can see, the format is consisted with:
#
#       "${addr}:hash_weight ${node_alias}"
#
# And, for redis_cluster you can set the item as:
#
# servers = ["127.0.0.1:7000", "127.0.0.1:7001"]
#
# which means the seed nodes to connect to redis cluster.

servers = ["127.0.0.1:6379"]

# Work thread number, it's suggested as the number of your cpu(hyper-thread) number.

thread = 1

# ReadTimeout is the socket read timeout which effects all in the socket in millisecond

read_timeout = 2000

# WriteTimeout is the socket write timeout which effects all in the socket in millisecond

write_timeout = 2000

############################# Cluster Mode Special #######################################################
# fetch means fetch interval for backend cluster to keep cluster info become newer.
# default 10 * 60 seconds

fetch = 600


# read_from_slave is the feature make slave balanced readed by client and ignore side effects.
read_from_slave = true

############################# Proxy Mode Special #######################################################
# ping_fail_limit means when ping fail reach the limit number, the node will be ejected from the cluster
# until the ping is ok in future.
# if ping_fali_limit == 0, means that close the ping eject feature.

ping_fail_limit=3

# ping_interval means the interval of each ping was send into backend node in millisecond.

```
